### ISSUE TITLE
[BUG]Battery discharge power dosn´t work correct

### ISSUE THREAD

**Issue by sebbihonk** [flixlix/power-flow-card-plus#217]
Hey,
the discharge power is wrong. That was calculated and not be used from the entity i use.
Best regards
Sebbi

**Comment by flixlix** [comment]
Can you explain that?

What code are you using?

What do you expect to happen?

What is happening?

Screenshots would also help 🙂

**Comment by sebbihonk** [comment]
i have 2 Solarplants an the battery entity shows automatic the Solarplant (secondary Info) - Homecomsumption. At the moment i have no discharge form the battery. Only cosumtion from the solarplant.

![konfig](https://github.com/flixlix/power-flow-card-plus/assets/118036862/78ec7c5b-5a40-44cd-acac-9df62182510b)


![card](https://github.com/flixlix/power-flow-card-plus/assets/118036862/3c0322a2-579b-4b88-ad31-19911ac123ce)

**Comment by sebbihonk** [comment]
Before the last update all was good.

**Comment by flixlix** [comment]
I am not able to replicate this issue. To me it is also not very clear what you are trying to achieve.
The value in the battery should never be negative.
Can you share your code for the configuration and the version you are using?

**Comment by flixlix** [comment]
I think I figured out the issue. You are exporting more to the grid, which is not a supported scenario. I get that you are trying to display both solar arrays, but I'm afraid for now you'll have to create a template sensor that sums both values to get a total value.

Furthermore, I don't think this worked in the previous versions, because this logic didn't change since then

**Comment by sebbihonk** [comment]
Ok. If i use one Solarplant its no Problem. Sorry. I will wait for the feature to use more Plants. 
Thanks for helping.
