### ISSUE TITLE
Feature request: Individual entities for solar

### ISSUE THREAD

**Issue by thomasvt1** [flixlix/power-flow-card-plus#23]
Really love this card!

But there's one thing that would make it even better, I have an [Enphase](https://enphase.com/) solar system which offers per-panel solar production figures. Now I understand that having 20 different entities is not feasable, but it would be nice to have one grouped entity per side of the roof. (In my case that would be East, South, West).

Would something like that be feasible?

Thanks!

**Comment by xsirpreisx** [comment]
I do have east and west sides as well (and I have 72 SolarEdge panel optimizers), but I don't think I would want this card to display both sides of the roof as separate entities, to be honest. 

I would think that some other card (that may pop up when clicking on the solar icon?) should/could display detailed information of the system. You could display detailed information for each direction and maybe even for each panel, but this power flow card will not be overcrowded.

Just my two cents.

**Comment by thomasvt1** [comment]
Maybe something similar to what we have for home?
![image](https://user-images.githubusercontent.com/2271011/227938802-6c78c728-2ab2-494b-95cc-bbb33bb41f52.png)

Multiple solar sources going to one entitiy?

**Comment by thomasvt1** [comment]
Maybe something similar to what we have for home?
![image](https://user-images.githubusercontent.com/2271011/227938802-6c78c728-2ab2-494b-95cc-bbb33bb41f52.png)

Multiple solar sources going to one entitiy?

**Comment by flixlix** [comment]
Could you maybe do a photoshop of that?
I think the main problem is that the solar production doesn't go into a single entity but instead into the grid, home and, in case you have it, battery... Plus, the top row already has three circles and, like @xsirpreisx said, would be overcrowded with even more circles... Maybe you have an idea on a possible solution?

**Comment by flixlix** [comment]
Can you share your code? I suspect you didn't enter a grid entity and that's why it's not working for you

**Comment by manofpants** [comment]
I'll move to the discussions so it won't detract from the feature req :)

**Comment by andynash** [comment]
I have a suggestion for making this work tidily yet displaying 2 x solar:

How about displaying the two solar sources in the same way as the battery production/consumption, i.e. two numeric values within the circle?

This may not suit those with more than two solar sources, or two sources plus a total (unless you allowed removing the solar icon perhaps?), but it would work for the majority who I suspect have no more than two strings/orientations (we have three orientations on two strings, but have no separate data sources for the two orientations on one string).

To identify the two sources, people could configure different icons in place of the up/down arrows for the battery, use different colors, or use text/ rather than an icon. You'd probably only fit one or two characters I guess, for example F[ront]/R[ear] or E[ast]/S[outh]W[est]. Personally I'd go for F and R, e.g.

F: 1.2 kW
R: 2.4 kW

**Comment by charles-sd** [comment]
My inverter features two string inputs. It only reports these as two discrete PV power sensors, and I have to create a custom sensor to add them together as a single entity for this card. Other models from the same manufacturer feature 4 strings, and with parallel inverters I trust it can get even more messy, not to mention optimizers that report their individual production.

I have a possible suggestion that should be simple to implement yet flexible:
Allow the user to configure an unbound array of Solar source entities and give each a text label.
e.g. 
```
  - solar:
    - inputs:
      - label: North
        entity: solar.array_1 
        position: top
      - label: South
        entity: solar.array_2 
        position: top
      - label: 'N East'
        entity: solar.array_3 
        position: top
```

The card could add their values together and display the total input value in the circle.
The inputs themselves could be displayed above the Solar circle. This avoids messing up the grid as long as the current top three cells are bottom aligned. It would extend the vertical size of the card at worst for those using the feature. Last image shows how the current grid could be used for positioning without breaking it,

![image](https://user-images.githubusercontent.com/87366874/233730556-8eb10985-aae2-4f56-bfae-68a577302a60.png)


OR 

![image](https://user-images.githubusercontent.com/87366874/233730890-07e34c00-9ef0-4e55-9065-a8f001ab236d.png)


With position implemented like this:

![image](https://user-images.githubusercontent.com/87366874/233732163-7ff1a5e5-686f-4fa3-9ace-df5dcc0d352e.png)

The items added to each off the 3 areas would be html formatted in some way to keep them compact, preventing the card from expanding when not desired, yet so that it does not cause major jumps when redrawing.

This could easily accommodate many of the use cases, as long as users are economical with the label lengths.

Thoughts?

**Comment by Obmawo** [comment]
Great Idea! Any news?

**Comment by JokerGermany** [comment]
@charles-sd I like the last one, because it's not only working good for the south, east, north, west example.

**Comment by thenebu** [comment]
I've got 8 Strings. Would be very nice if I can display them separately with a toggle (all, separat)

**Comment by RaoulSargent** [comment]
@charles-sd 
I like the diagram showing each individual PV source ("_something dynamic and pretty with Bezier curves_").
This would be in keeping with the overall design of the chart and have the ability to show the individual animated flows, again like the rest of the chart.

This also seems a far more flexible solution for people with many PV sources.  Sure you would not want to show more than would fit on the screen and look 'pretty', but you could easily combine into groups as required to compromise between having too many and showing enough detail.  

In my case I have 2x inverters and 3x strings.

![image](https://github.com/flixlix/power-flow-card-plus/assets/61843699/074c1d7d-234d-4bec-8add-244088bae917)

**Comment by schaubl** [comment]
Another use case would be when there are multiple solar installations with different contracts and/or different type of usage (for example one with full injection to the grid and another one with self consumption only or mixed, or one with a battery, etc).

**Comment by DangerTimsen** [comment]
This feature would be awesome on this beautiful card :) bump
