### ISSUE TITLE
Wrong numbers for home consumption (continued)

### ISSUE THREAD

**Issue by benvanmierloo** [flixlix/power-flow-card-plus#258]
Hi, 

it seems I have found an edge case linked to issue #231. 

When feeding all power (Solar + Battery) to the grid, the Home calculation not correct. In the screenshot below you can see the situation. 4.67 kW is being fed into the grid. The battery supplies 2.62 kW and the Solar panels 2.38 kW. This means the Home consumption should be Solar + Battery discharge - Grid injection (2.38kW+2.62kW-4.67kW) = 330W instead of 2.62kW,

![screenshot_discharge_to_grid](https://github.com/flixlix/power-flow-card-plus/assets/3785514/81ccef70-5200-4444-85c9-ccd21ae9db2f)

_Originally posted by @benvanmierloo in https://github.com/flixlix/power-flow-card-plus/issues/231#issuecomment-1578249782_

**Comment by flixlix** [comment]
Did this work in version 0.1.3?
Because this seems like a very strange scenario.
Why would you be exporting to the grid while producing from the battery?

**Comment by neildsb** [comment]
> Did this work in version 0.1.3? Because this seems like a very strange scenario. Why would you be exporting to the grid while producing from the battery?

I am currently on the 'Tesla Energy Plan' AKA 'virtual power plant' and get paid at peak rates to dump the battery to the grid

https://www.tesla.com/support/energy/powerwall/own/california-virtual-power-plant

**Comment by flixlix** [comment]
Can you check if this file solves the issue?

The Console **MUST** log the following:
![Console Version](https://github.com/flixlix/power-flow-card-plus/assets/61006057/22bb2a83-a721-4c6f-952e-ac1242e983f3)
Otherwise, you don't have the file is not being used. Check the instructions in the readme for a manual install and clear the cache of your browser.

[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/11679907/power-flow-card-plus.js.zip)

Would love to get some feedback, so I now if the issue is fixed and can push the changes to the next version

**Comment by neildsb** [comment]
no probs will check tomorrow, I will only know if it's working if- 

1. is ifs sunny in the UK (the weather is looking good BTW) and 
2. at 4pm BST...

I understand how to manually install, but, can I just copy the 'single' file (power-flow-card-plus.js) to the HACS dir that was created and reload....?

![image](https://github.com/flixlix/power-flow-card-plus/assets/91122872/44a94e74-a38f-4fbc-aa99-074313da7ae9)

**Comment by flixlix** [comment]
Just released the new version, which fixes this issue! 🥳

https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.5.2

**Comment by neildsb** [comment]
thanks, have pulled the update, Ii will feedback tomorrow at 4pm BST, thanks take care

**Comment by neildsb** [comment]
thanks, have pulled the update, I will feedback tomorrow at 4pm BST, thanks take care
