### ISSUE TITLE
Additional electricity generator

### ISSUE THREAD

**Issue by xen2** [flixlix/power-flow-card-plus#259]
**Is your feature request related to a problem? Please describe.**
I have an extra source of power that's not solar panel (residential fuel cell, it's called Enefarm in Japan).
It is part of the home and I think it can flow back to the grid just like solar panel (not 100% sure).

**Describe the solution you'd like**
Something like Individual 1 but for electricity generation rather than consumption or second icon next to solar panel.

**Describe alternatives you've considered**
I tried to add it as Individual 1 using a negative sensor template so that it gives me -700 if it's producing 700W.
But as soon as I do "Subtract individual" for the house value, it removes the 700W value from Home instead of adding it (because it does a Math.abs() on the value then a substraction.
![image](https://github.com/flixlix/power-flow-card-plus/assets/527565/2d40cb12-e284-4279-a2b1-b11419a5a60a)
It should display 963+700 = 1663 rather than 963 - 700 = 263

I guess another approach is to simply merge it with solar panel value. But ideally I would like to see both separate values.

**Comment by flixlix** [comment]
I will try to add this.
In the meantime, you can use `override_state`

**Comment by flixlix** [comment]
I just added this functionality and would like for you to test it.
The name `subtract_individual` doesn't make so much sense now, but to avoid breaking changes, I'll keep it in 😊

Can you check if this file solves the issue?

The Console **MUST** log the following:
![Console Version 0.1.5 - 259](https://github.com/flixlix/power-flow-card-plus/assets/61006057/55ee648e-58f2-4b07-ac9e-736c36872711)

Otherwise, you don't have the file is not being used. Check the instructions in the readme for a manual install and clear the cache of your browser.

[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/11680170/power-flow-card-plus.js.zip)

Would love to get some feedback, so I now if the issue is fixed and can push the changes to the next version

**Comment by flixlix** [comment]
Just released the new version, which fixes this issue! 🥳

https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.5.2
