### ISSUE TITLE
Without grid the view is a bit destroyed

### ISSUE THREAD

**Issue by geeuz** [flixlix/power-flow-card-plus#342]
Hi,

I have a self-sufficient island system without connection to the public grid, and without grid the view is a bit destroyed, maybe it can be fixed?
There is too much space on the left and the lines are not quite right.
But great frontend, thanks for your work!
![power_flow_card_plus](https://github.com/flixlix/power-flow-card-plus/assets/13900795/29b8bd4e-03e5-4135-b5dc-33e68003b94b)

**Comment by flixlix** [comment]
Nice find 😉
I noticed this occurs because the label of home disappears when two individual devices appear, so the spacing gets destroyed...

### Before:
![Before](https://github.com/flixlix/power-flow-card-plus/assets/61006057/7f0b6e9d-5a66-4c11-9b76-b88e257b8c8c)

### After:
![After](https://github.com/flixlix/power-flow-card-plus/assets/61006057/77a2642c-a136-410f-9d0b-8678f8b24e89)

Anyways, I fixed it in #343 
Will be available in the next release 🚀

**Comment by geeuz** [comment]
Wow, you are very fast! Thanks!!
