### ISSUE TITLE
[BUG] Fossil Fuel show current Value but should show daily percentage

### ISSUE THREAD

**Issue by Chris909090** [flixlix/power-flow-card-plus#429]
**Describe the bug**
As you could see in the picture, the value of the fossil fuel is the target. But it should show the average of the day.
![image](https://github.com/flixlix/power-flow-card-plus/assets/39734863/b2105230-5560-446c-8245-5ca270da47cc)

**Comment by flixlix** [comment]
hey there, I'm not sure I understand what you mean, but the card seems to be showing the correct amount of percentage that is non-fossil.

The card does not have access to the daily average and since this this card is used to display power only (kWh as shown are not supported) you should only be interested in the current percentage.

If you still wish to show the average you can create a custom sensor that averages these results throughout the day.
