### ISSUE TITLE
[FEATURE REQUEST] Be able to add more energy sources/objects/consumers

### ISSUE THREAD

**Issue by bjornarfjelldal** [flixlix/power-flow-card-plus#440]
Thanks for your great effort.

It would be a great feature to have more energy sources added, such as Wind, Hydro and others and to have an option on where they should connect (either to grid, to home/consumer and so on).

This could make this a fully capabale renewable energy production dashboard to use to simulate a combination of different energy sources, and how they affect the grid. 

Speaking of grid, there may also be cases where you have more than one grid/systems. This could of course be solved by adding another card, but sometimes they may interact with each other.

So a dynamic way of creating and connecting objects (source1, source2, sourceX, consumer1, consumer2, consumerX, grid1, grid2, gridX and so on) may be an end goal, however being able to manually add a few more energy sources and naming them would be very much appreciated.

**Comment by erepeo** [comment]
I'm asking you to do the same. I hope this plugin will have everything we need.

**Comment by flixlix** [comment]
Hey there, thank you very much for the kind words, I'm glad you like my card :)

I just released this https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.0-alpha
Still in alpha, but it implements multiple individual devices!

I am not planning on adding more grids or power sources, since I unfortunately only have very limited time to work on this card

**Comment by bjornarfjelldal** [comment]
Aweseome @flixlix, will check it out :)
