### ISSUE TITLE
[SUPPORT] I have a problem

### ISSUE THREAD

**Issue by Capitan022** [flixlix/power-flow-card-plus#482]
I'm experiencing a problem with my power flow card in Home Assistant. 

When there's minimal (180 W) consumption in my home, it seems that all the solar production and household consumption are being directed straight to the grid. However, when there's significantly more consumption, the card appears to function correctly again. I'll show two images to illustrate this issue.

<img width="412" alt="Captura de pantalla 2024-01-28 a las 15 12 06" src="https://github.com/flixlix/power-flow-card-plus/assets/113519081/1f0484ff-820b-4b4f-8a56-09c19777e487">
<img width="409" alt="Captura de pantalla 2024-01-28 a las 15 19 06" src="https://github.com/flixlix/power-flow-card-plus/assets/113519081/1f9c7438-4299-4b49-b98f-2b9419da5143">

**Comment by flixlix** [comment]
Hey, like @snigehere mentioned this seems like a configuration or sensor issue rather than a card issue.
If you are exporting 2,3kw to the grid, you need at least a source in your home that is exporting said power. In your first screenshot you are only producing 1,4kw which is not possible. One of those values is incorrect, or a battery is involved and not pictured
