### ISSUE TITLE
Fossil fuel percentage keeps showing import percentage when actually exporting

### ISSUE THREAD

**Issue by stijnpiron** [flixlix/power-flow-card-plus#55]
When setting `state_type: percentage` for `fossil_fuel_percentage`, the percentage value is still visible from when there was actual import from the grid. 
This feels wrong, not really sure what value should be displayed when exporting to the grid, feels like I would prefer no value in that case...
<img width="478" alt="image" src="https://user-images.githubusercontent.com/2921903/231126725-d28f4447-e6d7-4d32-b2f5-d10013f58d63.png">

**Comment by flixlix** [comment]
Can you please share the code of your card so I can somewhat debug the issue?

**Comment by flixlix** [comment]
The reason for this is that you have set `display_zero` to `true` and so the Non-Fossil Circle always appears. I would suggest you remove that line, so that the circle disappears in case your are returning to the grid. I decided to not have the percentage at 0 when exporting, since this is not really the case. In this scenario, you are exporting to the grid but that doesn't mean that the grid has 0% non Fossil Energy.
I think in either case / scenario, there will be tradeoffs... So I'll close this issue for now, but if you have other suggestions, feel free to open a PR with a new behaviour.
