### ISSUE TITLE
feature request - Show house load excluding EV charging 

### ISSUE THREAD

**Issue by SteveBrailsord** [flixlix/power-flow-card-plus#57]
Great card thanks you.
Would it be a good idea to have the net value of the household usage shown as well as the total, when using with a Car Charger for example ?
for example if the total household power draw is 2KW but 1.5 KW is going to charge the car, it could show 0.5 being used by the house?

**Comment by SteveBrailsord** [comment]
I wanted both entities to be shown, but can’t see how to add entities to
the home circle ?

**Comment by flixlix** [comment]
I'm sorry, you are correct, the home is only used for the tap action, but I still don't think this would be coherent design, since all "flow dots" flow through home to the individual devices, and no energy source has a direct connection to the individual devices.
I like people to be able to customize the card to their likings though, so I'll add this to the todo-list. Just know that this might take some time to release because (to me) it's not a top priority

**Comment by paulgee31** [comment]
I'll second @SteveBrailsord request as I find the inclusion of the individual entities in the home calculation misleading at a glance. I then have to perform some mental calculations to subtract the EV or solar hot water diverter to get the house load but agree being cable to customise the Home entities would a good solution.

Thanks for the secondary info on solar and the great work on this card ❤️

**Comment by SteveBrailsord** [comment]
Thank you

**Comment by flixlix** [comment]
Added this feature in this PR: #69 
Will be available in the next release 🦾🎉
