### ISSUE TITLE
Hide In-active lines

### ISSUE THREAD

**Issue by godfreym29** [flixlix/power-flow-card-plus#62]
Would it be possible to include an action to hide the lines between circles that are not currently active please?

**Comment by flixlix** [comment]
imho this would lead to a very inconsistent design in addition to being extremely difficult to implement. The small dots are indicators that power is flowing and as such, if there is no power flowing, there is also no movement. I think this is a pretty intuitive form of display... In the case of individual devices, if they are not taking in any power, the circle would be floating alone in the air and noone would be able to know where it is normally connected to. So, because of those reasons, unfortunately I don't think this will be an option I will be adding anytime soon... 😔
