### ISSUE TITLE
Broken Layout in IOS

### ISSUE THREAD

**Issue by popokio** [flixlix/power-flow-card-plus#648]
When all the individuals entities are present, the layout breaks. It happens only on my iphone 12. Both from ha app and browser. not on android Samsung A53...  (tried opening the same dashboard on both devices)
Tested with latest iOS,app,and card version.

Home assistant - Qnap - Docker
Core 2024.3.1
Frontend 20240307.0

I attach a screenshot from iphone
![Screenshot](https://github.com/flixlix/power-flow-card-plus/assets/56551838/2f78d437-e969-4d75-b663-12d51d37842c)

**Comment by flixlix** [comment]
Hey @popokio this is an expected behaviour and has nothing to do with your phone being IOS vs Android.

You can see in the screenshot, the bubbles have no space left between each other so they start taking up more space towards the left.

This is happening only because your phone screen is too small to display that many individuals.

Thank you for your understanding
