### ISSUE TITLE
[OTHER] Secondary_info entities only display whole numbers

### ISSUE THREAD

**Issue by shammond-uk** [flixlix/power-flow-card-plus#76]
Thanks so much for adding the secondary_info option on all bubbles in the latest beta. This is very useful, but I note that irrespective of the data type of the entity being displayed, it rounds values to the nearest whole number. This behaviour is not in line with the other existing primary entities which round to one decimal place. Would be really useful if you could bring the secondary_info entities in line with the primaries and support decimals. Thanks

**Comment by flixlix** [comment]
Thank you very much for your support and suggestion.
I like this idea, but I think this would get out of hand really quickly, because there are unlimited scenarios in which the `secondary_info` can be used. I would still like for people to have the option to go crazy advanced, so I had an idea:
How about an option in which users can enter any [Template](https://www.home-assistant.io/docs/configuration/templating/) they want and whatever the output of that template is, will be displayed in the `secondary_info` field?

**Comment by TrilIiard** [comment]
That would open up a whole new Level

**Comment by tomas-dorda** [comment]
That would be great! I would like to use the `secondary_info` for grid current tarif. Which is string `NT` or `VT` which is currently not possible. Thanks for the great project!
