### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tigers75** [flixlix/power-flow-card-plus#84]
I must say I like the card very much, it has a lot of potential but still lacks some polishing. I can't program in phyton css or java so I'm sorry I can directly be of help, but I'd like to try to point out what I'd like to see implemented and how, hoping someone will pick this up.
First of all the secondary info seems to work a little hit and miss for me: numeric values are OK, non numeric sensor... It depends, I think maybe some bubbles can elaborate string sensors, other can't. The templating solution I saw in some PR will fix this, so I'll wait.
Second: at the moment I'm using another similar card for power flow  [https://github.com/reptilex/tesla-style-solar-power-card](url), and I'd like to point out what I like in that card that isn't in this one:

- the flow speed in the other card is perfect and auto fit itself, no need to configure anything and it just works: I'd take a look at the code and try to replicate. In this car it's still buggy: the dots move at different speeds even between bubbles I just cant' find a way to make it look right for low power or high power;
- it has an option to make unused lines disappear: it's much more clear for a power card (the original card is for energy so it makes sense that all the lines are there all the time, here's a comparison of the 2 cards, to me is so much clearer what's going on in the second image:
![image](https://user-images.githubusercontent.com/37505492/232314870-3c26f66f-6f10-49e0-95af-90e8649ac931.png)

**Comment by flixlix** [comment]
Thank you for your suggestions. In the future, please open one issue for each suggestion, otherwise it's hard to keep track of each suggestion. Another option is to open a Discussion if you don't know exactly how to fix the issues / introduce the features.

> non numeric sensor... It depends, I think maybe some bubbles can elaborate string sensors, other can't.

Can you explain what you mean by this?

> The templating solution I saw in some PR will fix this, so I'll wait.

Yes, hopefully that'll fix the issues you're experiencing.  Keep in mind that there is very limited space inside the circles, so you can't add a giant text, otherwise it will overflow and have ellipsis at the end of the string.

> the flow speed in the other card is perfect and auto fit itself, no need to configure anything

What do you mean by "auto fit"?
I also am going to release a new flow rate model in the next release which is linear and based on absolute values, maybe that'll work better.

> option to make unused lines disappear

This has been requested before, but I just think that from a UI perspective, things seem more balanced that way. 
It's like in the real world: Just because there's a cable between a source and a consumer (in this scenario, a line between a source and home), doesn't mean there is power flowing. I think the power of this card is the fact that you have the animations. Just by looking at a screenshot, you obviously can't tell, what is flowing.
That being said, if you really want this functionality, feel free to open a PR (or ask someone in the community to do it) to add it and I will gladly add it as an option, but not as default behavior, for the reasons I just mentioned.

**Comment by tigers75** [comment]
> 



> > non numeric sensor... It depends, I think maybe some bubbles can elaborate string sensors, other can't.
> 
> Can you explain what you mean by this?
> 
> > The templating solution I saw in some PR will fix this, so I'll wait.
> 
> Yes, hopefully that'll fix the issues you're experiencing. Keep in mind that there is very limited space inside the circles, so you can't add a giant text, otherwise it will overflow and have ellipsis at the end of the string.

I have a sensor that reports the active tariff, it's just a 2 character (F1, F2, F3) but if i indicate this sensor as secondary_info it doesn't show up inside the bubble. If I select a numeric sensor like battery percentage it shows up just fine. But as I said I'll wait for the next version, templating is a welcomed upgrade and it'll fix everything.

> What do you mean by "auto fit"?

I mean I don't have to feed it with many values like max expected flow, etc., but still it manages to handle the dots speed better: it's more consistent and uniform across the bubbles. There's a single "speed" parameter I set up once and forget about it, I had to make several tries with this card and still it doesn't seem consistent when power flow variates and across bubbles, but I'm still experimenting so...



> > option to make unused lines disappear
> 
> This has been requested before, but I just think that from a UI perspective, things seem more balanced that way. It's like in the real world: Just because there's a cable between a source and a consumer (in this scenario, a line between a source and home), doesn't mean there is power flowing. I think the power of this card is the fact that you have the animations. Just by looking at a screenshot, you obviously can't tell, what is flowing. That being said, if you really want this functionality, feel free to open a PR (or ask someone in the community to do it) to add it and I will gladly add it as an option, but not as default behavior, for the reasons I just mentioned.

Well, I'm in no way suggesting this should be default, but from a UI perspective I think just the opposite: it's an instant power flow representation, and eliminating the line adds clarity to it (again: this is not the case with the standard card, which is about energy); the power of the card is both in the animations and in the information that it can give at a glance: what is powering what (the change of color in the icons according to what's the flow of power: I like it very much, the pie chart around the house: I like very much).
Also what you say seems not coherent with the presence of display_zero and zero_tolerance options: why eliminate them when they are zero? why not leave the lines?

As I said I never programmed in Java, but since you said many asked I'll give it a try and see if I can add this as an option and send a PR.

Thanks.

**Comment by flixlix** [comment]
> don't have to feed it with many values like max expected flow

Like I said, hopefully the new flow rate model suits your scenario better. That just means that the default parameters from my card need to be adjusted, once again, when the new version releases, feel free to submit a PR suggesting new default parameters.
I have seen the code from the Tesla Power Card, and I get that it's easier to just have one parameter to configure like `speed`, but I see it as a downgrade if people can't customize every aspect of the card. The default parameters are there, but if your house has exceptionally high power demands, you should absolutely be able to change them. I personally like having options to configure, even if most people aren't even going to touch them.

**Comment by flixlix** [comment]
I just added this implementation in a new PR #87 
![Bildschirmfoto 2023-04-16 um 19 52 53](https://user-images.githubusercontent.com/61006057/232332202-aff43654-20a3-4b54-980a-5c4d84def590.png)
I don't think I'm going to merge it, because this will lead to scenarios like this:
![Bildschirmfoto 2023-04-16 um 19 52 59](https://user-images.githubusercontent.com/61006057/232332201-a4021aeb-5cd0-45a0-b798-fc92670cbac2.png)
Where the `battery` bubble is just floating around in the middle of nowhere if it's fully charged

**Comment by tigers75** [comment]
Well, that might surprise you but that's exactly what I want, the same would happen to the solar panels during the night and to the grid during the day. With a quick glance I can see what is drawing power and where from. 
I think a "display_zero_lines" boolean could satisfy everyone.

**Comment by flixlix** [comment]
I don't think `display_zero_lines` is a very fitting option, because the default behavior should do exactly that. So it would be weird to have this as default `true`, because in the YAML would you have to set it to false...

**Comment by flixlix** [comment]
updated the PR #87 to also hide the `low_carbon` and both `individual` lines

**Comment by flixlix** [comment]
Currently looks like this:
![Bildschirmfoto 2023-04-17 um 00 20 55](https://user-images.githubusercontent.com/61006057/232345963-2f525d6e-c6e9-4a2f-ba41-0d1720bec184.png)
Added `display_zero_state` functionality in this PR #88 
Allows you to choose wether or not to hide the state in case the entity has a value of `0`

**Comment by tigers75** [comment]
> I don't think `display_zero_lines` is a very fitting option, because the default behavior should do exactly that. So it would be weird to have this as default `true`, because in the YAML would you have to set it to false...

I just followed what's already in the card for the "display_zero" option (that defaults to false); I think that since these 2 option do basically the same thing for 2 different objects it'd be better to maintain the same logic.

**Comment by flixlix** [comment]
Renamed this option
